### ISSUE TITLE
Зачем /ajax/config.json

### ISSUE THREAD

**Issue by Urzhumtsev1** [roschat/roschat-docs#1]
Не понятны цели GET запроса /ajax/config.json на сервер. Так например я отправляю GET на https://ormp.ros.chat и получаю ответ {webSocketsPort: 8080}. Что мне дальше с этим делать?

**Comment by MarkFomin** [comment]
Предполагалось, что порты для http запросов и событий на socket.io могут отличаться. Для этого был сделан запрос получения конфигурации сервера - [/ajax/config.json](https://github.com/roschat/roschat-docs/wiki/roschat-bot-api-http-ajax-config.json).
